pipeline {
    agent any
    stages {
        stage('Checkout GIT') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: 'https://github.com/Sahargaichee/catgory_product.git']]
                ])
            }
        }

        stage('MVN CLEAN') {
            steps {
                bat 'mvn clean'
                    }
                            }
            stage('MVN COMPILE') {
                    steps {
                        bat 'mvn compile'
                    }
                }

                stage('MVN PACKAGE') {
                    steps {
                        bat 'mvn package'
                    }
                }

                stage('MVN TEST') {
                    steps {
                        bat 'mvn test'
                    }

                }
                  stage('MVN SONARQUBE') {
                                             steps {
                                         bat 'mvn clean verify sonar:sonar \
                                               -Dsonar.projectKey=sahar \
                                               -Dsonar.host.url=http://localhost:9000 \
                                               -Dsonar.login=sqp_9cedb2cae0ff038c1d0aa81d83948fa492ff0e90'
                                                                   }
                                                               }
                                     stage('Docker login') {

                                                            steps {
                                                             bat 'echo "login Docker ...."'
                                                              bat 'docker login -u saharga -p sahar1998'
                                                                         }  }

                                                         stage('Build docker image'){
                                                            steps{
                                                                    script{
                                                                bat 'docker build -t saharga/produit-1.0.0:latest .'
                                                                                                                           }
                                                                                                                         }
                                                                                                                     }
                            	 stage('Docker push'){
                                                  steps{
                                                           bat 'echo " Docker is pushing ...."'
                                                             bat 'docker push saharga/produit-1.0.0:latest'

                                                                            }
                                                                        }

                  }
                                }